---
# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length: disable
  # Accept both `true` and `yes` for boolean values
  truthy:
    check-keys: false
  # Fix yamllint requirements
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
