# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1

# Computer-generated files and other files which cannot be copyrighted
[[annotations]]
path = [
    ".ansible-lint",
    ".codespellrc",
    ".dockerignore",
    ".editorconfig",
    ".github/renovate.json",
    ".github/workflows/pre-commit.yml",
    ".gitignore",
    ".pre-commit-config.yaml",
    ".woodpecker.yml",
    ".yamllint.yml",
    "meta/main.yml"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
