# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure LittleLink Server base directory exists
  ansible.builtin.file:
    path: "{{ littlelink_server_base_path }}"
    state: directory
    mode: '0755'
    owner: "{{ littlelink_server_uid | default(omit) }}"
    group: "{{ littlelink_server_gid | default(omit) }}"

- name: Ensure LittleLink Server data directory exists
  ansible.builtin.file:
    path: "{{ littlelink_server_data_path }}"
    state: directory
    mode: '0755'
    owner: "{{ littlelink_server_uid | default(omit) }}"
    group: "{{ littlelink_server_gid | default(omit) }}"

- name: Create LittleLink Server container network
  community.docker.docker_network:
    name: "{{ littlelink_server_container_network }}"
    state: present
    driver: bridge
    internal: false
    enable_ipv6: false

- name: Generate LittleLink Server environment file
  ansible.builtin.template:
    src: env.j2
    dest: "{{ littlelink_server_base_path }}/env"
    mode: '0644'
    owner: "{{ littlelink_server_uid | default(omit) }}"
    group: "{{ littlelink_server_gid | default(omit) }}"
  notify: restart littlelink_server

- name: Generate LittleLink Server container labels file
  ansible.builtin.template:
    src: labels.j2
    dest: "{{ littlelink_server_base_path }}/labels"
    mode: '0644'
    owner: "{{ littlelink_server_uid | default(omit) }}"
    group: "{{ littlelink_server_gid | default(omit) }}"
  notify: restart littlelink_server

- name: Generate LittleLink Server systemd service file
  ansible.builtin.template:
    src: littlelink_server.service.j2
    dest: "/etc/systemd/system/{{ littlelink_server_identifier }}.service"
    mode: '0644'
  notify: restart littlelink_server

- name: Ensure LittleLink Server systemd service is enabled and started
  ansible.builtin.systemd:
    name: "{{ littlelink_server_identifier }}"
    state: started
    enabled: true
    daemon_reload: true
