# SPDX-FileCopyrightText: 2025 Pavel Dimov <@sagat79>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
name: Deploy to Ansible Galaxy

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write
  packages: write

jobs:
  deploy:
    name: Deploy to Ansible Galaxy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: main

      - name: Debug workflow trigger
        run: |
          echo "=== Debug Information ==="
          echo "Event name: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref name: ${{ github.ref_name }}"
          echo "SHA: ${{ github.sha }}"
          echo "Branch: main"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Ansible and collections
        run: |
          pip install ansible
          ansible-galaxy collection install -r requirements.yml

      - name: Publish to Ansible Galaxy
        env:
          GALAXY_TOKEN: ${{ secrets.ANSIBLE_GALAXY_TOKEN }}
        run: |
          ansible-galaxy role import \
            --api-key $GALAXY_TOKEN \
            derfeldev \
            ansible-role-littlelink-server

      - name: Summary
        run: |
          echo "=== Deployment Summary ==="
          echo "Event: ${{ github.event_name }}"
          echo "Branch: main"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          echo "Status: Deployed to Ansible Galaxy from main branch"
